services:
  db:
    image: postgres:16-alpine
    container_name: limex-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: limex
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - limex-postgres-data:/var/lib/postgresql/data

volumes:
  limex-postgres-data:
