services:
  db:
    image: mysql:8.4
    container_name: limex-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: limex
      MYSQL_USER: limex
      MYSQL_PASSWORD: limex
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - limex-mysql-data:/var/lib/mysql

volumes:
  limex-mysql-data:
