"use client";

import { useEffect, useMemo, useState, type ReactNode } from "react";

import {
  createBlankTemplate,
  createTemplateId,
  type AdminDocumentTemplate,
  type DocumentTemplateDraft,
  type TemplateBlock,
  type TemplateField,
  type TemplateFieldType,
  type TemplateFontSize,
  type TemplatePage,
  type TemplatePageSettings,
} from "@/lib/document-templates";
import {
  checkTemplateSlug,
  createAdminTemplate,
  getAdminTemplates,
  publishAdminTemplate,
  unpublishAdminTemplate,
  updateAdminTemplate,
} from "@/lib/template-api";
import { ApiError } from "@/lib/menu-api";
import { DocumentTemplatePaper } from "@/components/limex/document-template-paper";

const inputClass = "h-10 w-full rounded-[10px] border border-[#d8d2c8] bg-white px-3 text-[12.5px] font-medium text-[#242129] shadow-[0_1px_2px_rgba(44,36,31,0.04)] outline-none transition-[border-color,box-shadow] placeholder:text-[#a29b92] hover:border-[#bdb4aa] focus:border-[#e44762] focus:ring-4 focus:ring-[#f8d9de]";
const areaClass = "min-h-20 w-full resize-y rounded-[10px] border border-[#d8d2c8] bg-white px-3 py-2.5 text-[12.5px] font-medium leading-[1.5] text-[#242129] shadow-[0_1px_2px_rgba(44,36,31,0.04)] outline-none transition-[border-color,box-shadow] placeholder:text-[#a29b92] hover:border-[#bdb4aa] focus:border-[#e44762] focus:ring-4 focus:ring-[#f8d9de]";
const labelClass = "block text-[11px] font-bold uppercase tracking-[0.13em] text-[#756e66]";
const fontSizeOptions: Array<[TemplateFontSize, string]> = [["small", "Small"], ["body", "Body"], ["subtitle", "Subtitle"], ["title", "Title"], ["large", "Title (legacy)"]];

function Field({ label, value, onChange, placeholder, type = "text" }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; type?: string }) {
  return <label className={labelClass}>{label}<input className={`${inputClass} mt-1.5`} type={type} value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} /></label>;
}

function Area({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string }) {
  return <label className={labelClass}>{label}<textarea className={`${areaClass} mt-1.5`} value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} /></label>;
}

function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) {
  return <label className="inline-flex cursor-pointer items-center gap-2 text-[13px] font-semibold text-[#5d5852]"><input className="peer sr-only" type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /><span className="relative h-5 w-9 rounded-full bg-[#d7d1c8] transition-colors peer-checked:bg-[#e44762] after:absolute after:left-0.5 after:top-0.5 after:size-4 after:rounded-full after:bg-white after:shadow-sm after:transition-transform peer-checked:after:translate-x-4" aria-hidden="true" />{label}</label>;
}

function SectionCard({ title, description, children, action }: { title: string; description?: string; children: ReactNode; action?: ReactNode }) {
  return <section className="rounded-[16px] border border-[#e5dfd7] bg-white p-3.5 sm:p-4"><div className="flex flex-wrap items-start justify-between gap-2.5"><div><h2 className="font-brand text-[18px] font-bold tracking-[-0.025em] text-[#17151c]">{title}</h2>{description ? <p className="mt-1 max-w-[700px] text-[11px] leading-[1.45] text-[#817a72]">{description}</p> : null}</div>{action}</div><div className="mt-3">{children}</div></section>;
}

function isFormattedBlock(block: TemplateBlock): block is Extract<TemplateBlock, { type: "title" | "heading" | "paragraph" | "field" }> {
  return block.type === "title" || block.type === "heading" || block.type === "paragraph" || block.type === "field";
}

function makeField(type: TemplateFieldType, index: number): TemplateField {
  const key = `field_${index + 1}`;
  return { id: createTemplateId("field"), key, label: "New field", type, required: false, placeholder: "", options: type === "select" ? [{ value: "option_1", label: "Option 1" }] : [] };
}

type EditableBlockType = Exclude<TemplateBlock["type"], "pageBreak">;

function makeBlock(type: EditableBlockType, fields: TemplateField[], index: number, defaultFontSize: TemplateFontSize): TemplateBlock {
  if (type === "field") return { id: createTemplateId("block"), type, fieldKey: fields[0]?.key ?? "field_1", align: "left", bold: false, italic: false, fontSize: defaultFontSize };
  if (type === "spacer") return { id: createTemplateId("block"), type, height: 24 };
  if (type === "signature") return { id: createTemplateId("block"), type, label: "Signature — {{party_a}}" };
  return { id: createTemplateId("block"), type, text: type === "title" ? "DOCUMENT TITLE" : type === "heading" ? `${index + 1}. New section` : "Write the document text here. Use {{field_key}} for dynamic values.", align: type === "title" ? "center" : "left", bold: type !== "paragraph", italic: false, fontSize: type === "title" ? "title" : type === "heading" ? "subtitle" : defaultFontSize };
}

function makePage(index: number, defaultFontSize: TemplateFontSize): TemplatePage {
  return { id: createTemplateId("page"), title: `Page ${index + 1}`, settings: {}, blocks: [makeBlock("paragraph", [], 0, defaultFontSize)] };
}

function updateBlock(blocks: TemplateBlock[], id: string, patch: Partial<TemplateBlock>) {
  return blocks.map((block) => block.id === id ? { ...block, ...patch } as TemplateBlock : block);
}

function parseOptions(value: string) {
  return value.split("\n").map((line) => {
    const [optionValue, ...labelParts] = line.split("|");
    return { value: (optionValue ?? "").trim(), label: labelParts.join("|").trim() || (optionValue ?? "").trim() };
  }).filter((option) => option.value && option.label);
}

function SortButtons({ index, count, onMove, onRemove }: { index: number; count: number; onMove: (direction: -1 | 1) => void; onRemove: () => void }) {
  return <div className="flex shrink-0 gap-1 sm:flex-col"><button className="grid size-7 place-items-center rounded-md border border-[#e3ddd4] text-[12px] text-[#6a645d] transition-colors hover:border-[#e44762] hover:text-[#e44762] disabled:opacity-30" type="button" aria-label="Move up" disabled={index === 0} onClick={() => onMove(-1)}>↑</button><button className="grid size-7 place-items-center rounded-md border border-[#e3ddd4] text-[12px] text-[#6a645d] transition-colors hover:border-[#e44762] hover:text-[#e44762] disabled:opacity-30" type="button" aria-label="Move down" disabled={index === count - 1} onClick={() => onMove(1)}>↓</button><button className="grid size-7 place-items-center rounded-md border border-transparent text-[15px] text-[#a59d94] transition-colors hover:border-[#f0c7ce] hover:text-[#c63d58]" type="button" aria-label="Remove" onClick={onRemove}>×</button></div>;
}

function BlockEditor({ block, fields, index, count, onChange, onMove, onRemove, onDragStart, onDragEnd }: { block: TemplateBlock; fields: TemplateField[]; index: number; count: number; onChange: (patch: Partial<TemplateBlock>) => void; onMove: (direction: -1 | 1) => void; onRemove: () => void; onDragStart: () => void; onDragEnd: () => void }) {
  const formatted = isFormattedBlock(block);
  const textBlock = block.type === "title" || block.type === "heading" || block.type === "paragraph";
  const text = textBlock ? block.text : "";
  const label = block.type === "paragraph" ? "Text" : block.type === "heading" ? "Heading" : block.type === "title" ? "Title" : block.type === "field" ? "Dynamic field" : block.type === "signature" ? "Signature" : "Spacer";

  return <div className="rounded-[15px] border border-[#e3ddd4] bg-white p-3 sm:p-4"><div className="flex items-start gap-2.5"><span className="mt-1 cursor-grab select-none text-[18px] leading-none text-[#aaa198]" title="Drag to reorder" aria-label="Drag section to reorder" draggable onDragStart={onDragStart} onDragEnd={onDragEnd}>⠿</span><div className="min-w-0 flex-1 space-y-3"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-[#f5eee9] px-2.5 py-1 text-[11px] font-bold uppercase tracking-[0.12em] text-[#776c61]">{label}</span>{textBlock ? <span className="text-[12px] text-[#9a9187]">Use <code className="rounded bg-[#f4f1ec] px-1">{'{{field_key}}'}</code> for dynamic text.</span> : null}</div>
    {textBlock ? (block.type === "paragraph" ? <textarea className={areaClass} value={text} onChange={(event) => onChange({ text: event.target.value })} /> : <input className={inputClass} value={text} onChange={(event) => onChange({ text: event.target.value })} />) : null}
    {formatted ? <div className="flex flex-wrap items-center gap-2"><button className={`rounded-full border px-3 py-1.5 text-[12px] font-bold transition-colors ${block.bold ? "border-[#17151c] bg-[#17151c] text-white" : "border-[#ddd6cd] text-[#69635c] hover:border-[#17151c]"}`.trim()} type="button" onClick={() => onChange({ bold: !block.bold })}>Bold</button><button className={`rounded-full border px-3 py-1.5 text-[12px] font-bold italic transition-colors ${block.italic ? "border-[#17151c] bg-[#17151c] text-white" : "border-[#ddd6cd] text-[#69635c] hover:border-[#17151c]"}`.trim()} type="button" onClick={() => onChange({ italic: !block.italic })}>Italic</button><select className="h-8 rounded-full border border-[#ddd6cd] bg-white px-2.5 text-[12px] font-semibold text-[#69635c]" value={block.align} onChange={(event) => onChange({ align: event.target.value as "left" | "center" | "right" })}><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option></select><select className="h-8 rounded-full border border-[#ddd6cd] bg-white px-2.5 text-[12px] font-semibold text-[#69635c]" value={block.fontSize} onChange={(event) => onChange({ fontSize: event.target.value as TemplateFontSize })}>{fontSizeOptions.map(([value, optionLabel]) => <option value={value} key={value}>{optionLabel}</option>)}</select></div> : null}
    {textBlock && fields.length ? <div className="flex flex-wrap items-center gap-2 border-t border-[#eee9e2] pt-2.5"><span className="text-[11px] font-bold uppercase tracking-[0.1em] text-[#978e84]">Insert field</span>{fields.slice(0, 8).map((field) => <button className="rounded-full bg-[#f2f7f3] px-2.5 py-1.5 text-[11px] font-semibold text-[#29634d] transition-colors hover:bg-[#dff0e5]" type="button" key={field.id} onClick={() => onChange({ text: `${text}${text && !text.endsWith(" ") ? " " : ""}{{${field.key}}}` })}>{field.label}</button>)}</div> : null}
    {block.type === "field" ? <label className={labelClass}>Dynamic field<select className={`${inputClass} mt-1.5`} value={block.fieldKey} onChange={(event) => onChange({ fieldKey: event.target.value })}><option value="">Choose a field</option>{fields.map((field) => <option value={field.key} key={field.id}>{field.label} · {field.key}</option>)}</select></label> : null}
    {block.type === "spacer" ? <label className={labelClass}>Space height (px)<input className={`${inputClass} mt-1.5`} type="number" min={4} max={240} value={block.height} onChange={(event) => onChange({ height: Number(event.target.value) })} /></label> : null}
    {block.type === "signature" ? <Field label="Signature label" value={block.label} onChange={(value) => onChange({ label: value })} placeholder="Signature — {{party_a}}" /> : null}
  </div><SortButtons index={index} count={count} onMove={onMove} onRemove={onRemove} /></div></div>;
}

function BlockList({ blocks, fields, onChange }: { blocks: TemplateBlock[]; fields: TemplateField[]; onChange: (blocks: TemplateBlock[]) => void }) {
  const [dragId, setDragId] = useState<string | null>(null);
  function move(id: string, direction: -1 | 1) { const index = blocks.findIndex((block) => block.id === id); const target = index + direction; if (index < 0 || target < 0 || target >= blocks.length) return; const next = [...blocks]; [next[index], next[target]] = [next[target], next[index]]; onChange(next); }
  function drop(targetId: string) { if (!dragId || dragId === targetId) return; const from = blocks.findIndex((block) => block.id === dragId); const to = blocks.findIndex((block) => block.id === targetId); if (from < 0 || to < 0) return; const next = [...blocks]; const [moved] = next.splice(from, 1); next.splice(to, 0, moved); onChange(next); setDragId(null); }
  return <div className="grid gap-2.5 sm:grid-cols-2">{blocks.map((block, index) => <div key={block.id} onDragOver={(event) => event.preventDefault()} onDrop={() => drop(block.id)} className={`${dragId === block.id ? "rounded-[16px] ring-2 ring-[#f3b8c0]" : ""} ${block.type === "signature" ? "" : "sm:col-span-2"}`.trim()}><BlockEditor block={block} fields={fields} index={index} count={blocks.length} onChange={(patch) => onChange(updateBlock(blocks, block.id, patch))} onMove={(direction) => move(block.id, direction)} onRemove={() => onChange(blocks.filter((item) => item.id !== block.id))} onDragStart={() => setDragId(block.id)} onDragEnd={() => setDragId(null)} /></div>)}</div>;
}

function FieldsEditor({ fields, onChange }: { fields: TemplateField[]; onChange: (fields: TemplateField[]) => void }) {
  function update(id: string, patch: Partial<TemplateField>) { onChange(fields.map((field) => field.id === id ? { ...field, ...patch } : field)); }
  return <div className="space-y-2.5">{fields.length ? fields.map((field) => <div className="rounded-[14px] border border-[#e3ddd4] bg-white p-3" key={field.id}><div className="grid gap-2.5 sm:grid-cols-[minmax(0,1fr)_150px]"><div className="grid gap-2.5 sm:grid-cols-2"><Field label="Label" value={field.label} onChange={(label) => update(field.id, { label })} /><Field label="Key" value={field.key} onChange={(key) => update(field.id, { key: key.toLowerCase().replace(/[^a-z0-9_]/g, "_") })} placeholder="party_name" /></div><label className={labelClass}>Input type<select className={`${inputClass} mt-1.5`} value={field.type} onChange={(event) => update(field.id, { type: event.target.value as TemplateFieldType, options: event.target.value === "select" ? field.options.length ? field.options : [{ value: "option_1", label: "Option 1" }] : [] })}><option value="text">Short text</option><option value="textarea">Long text</option><option value="date">Date</option><option value="number">Number</option><option value="select">Dropdown</option><option value="checkbox">Checkbox</option></select></label></div><div className="mt-2.5 grid gap-2.5 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-end"><Field label="Placeholder" value={field.placeholder} onChange={(placeholder) => update(field.id, { placeholder })} /><div className="flex items-center justify-between gap-3"><Toggle label="Required" checked={field.required} onChange={(required) => update(field.id, { required })} /><button className="rounded-full px-2 py-1 text-[12px] font-semibold text-[#b13c53] hover:bg-[#fff0f2]" type="button" onClick={() => onChange(fields.filter((item) => item.id !== field.id))}>Remove</button></div></div>{field.type === "select" ? <label className={`${labelClass} mt-2.5 block`}>Options — value | label per line<textarea className={`${areaClass} mt-1.5 min-h-16`} value={field.options.map((option) => `${option.value} | ${option.label}`).join("\n")} onChange={(event) => update(field.id, { options: parseOptions(event.target.value) })} /></label> : null}</div>) : <div className="rounded-[12px] border border-dashed border-[#d6cec4] bg-white p-4 text-[12px] text-[#817970]">No user fields yet. Add one when the document needs input.</div>}</div>;
}

function TemplateInputsCard({ fields, onChange, onAdd }: { fields: TemplateField[]; onChange: (fields: TemplateField[]) => void; onAdd: () => void }) {
  const [open, setOpen] = useState(false);

  useEffect(() => {
    if (!open) return;
    const closeOnEscape = (event: KeyboardEvent) => { if (event.key === "Escape") setOpen(false); };
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    document.addEventListener("keydown", closeOnEscape);
    return () => { document.body.style.overflow = previousOverflow; document.removeEventListener("keydown", closeOnEscape); };
  }, [open]);

  return <>
    <button className="group w-full rounded-[14px] border border-[#dfe8e1] bg-[#f7fbf8] p-3.5 text-left transition-colors hover:border-[#b8d3be] hover:bg-[#f2f9f3] focus:outline-none focus:ring-4 focus:ring-[#e2f0e4]" type="button" onClick={() => setOpen(true)} aria-haspopup="dialog" aria-expanded={open}>
      <span className="flex items-center gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-[11px] bg-[#dff0e3] text-[15px] font-bold text-[#2d7650]">ƒ</span><span className="min-w-0 flex-1"><span className="flex flex-wrap items-center gap-2"><span className="text-[13px] font-bold text-[#203b2d]">Template inputs</span><span className="rounded-full bg-[#e5f3e8] px-2 py-0.5 text-[9px] font-bold uppercase tracking-[0.12em] text-[#2d7650]">Global</span></span><span className="mt-1 block truncate text-[11px] text-[#6d7e72]">Shared across every page · {fields.length ? `${fields.length} input${fields.length === 1 ? "" : "s"}` : "No inputs yet"}</span></span><span className="flex shrink-0 items-center gap-2"><span className="rounded-full bg-white px-2.5 py-1 text-[11px] font-bold text-[#2d7650] shadow-[0_1px_2px_rgba(44,36,31,0.06)]">Manage</span><span className="text-[18px] text-[#71917a] transition-transform group-hover:translate-x-0.5" aria-hidden="true">→</span></span></span>
      {fields.length ? <span className="mt-3 flex flex-wrap gap-1.5 border-t border-[#e1eee3] pt-2.5">{fields.slice(0, 4).map((field) => <span className="rounded-full bg-white px-2 py-1 text-[10px] font-semibold text-[#55705d]" key={field.id}>{field.label}</span>)}{fields.length > 4 ? <span className="rounded-full bg-[#e5f3e8] px-2 py-1 text-[10px] font-semibold text-[#55705d]">+{fields.length - 4} more</span> : null}</span> : null}
    </button>
    {open ? <div className="fixed inset-0 z-[80] flex items-end justify-center bg-[#17151c]/35 p-2 backdrop-blur-[2px] sm:items-center sm:p-5" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setOpen(false); }}><section className="flex max-h-[92vh] w-full max-w-[820px] flex-col overflow-hidden rounded-[20px] border border-[#ddd6cd] bg-[#fbfaf7] shadow-[0_24px_80px_rgba(23,21,28,0.22)]" role="dialog" aria-modal="true" aria-labelledby="template-inputs-title" onMouseDown={(event) => event.stopPropagation()}><header className="flex items-start justify-between gap-4 border-b border-[#e8e2da] bg-white px-4 py-4 sm:px-5"><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#2d7650]">Global fields</p><h2 id="template-inputs-title" className="mt-1 font-brand text-[22px] font-bold tracking-[-0.03em] text-[#17151c]">Template inputs</h2><p className="mt-1 text-[11px] leading-[1.45] text-[#817970]">Available to every page and section in this document.</p></div><div className="flex items-center gap-2"><span className="rounded-full bg-[#edf5ef] px-2.5 py-1.5 text-[10px] font-bold text-[#2d7650]">{fields.length} total</span><button className="grid size-8 place-items-center rounded-full border border-[#e0d9d0] text-[17px] text-[#70675f] transition-colors hover:border-[#e44762] hover:text-[#e44762]" type="button" aria-label="Close template inputs" onClick={() => setOpen(false)}>×</button></div></header><div className="min-h-0 flex-1 overflow-y-auto p-3 sm:p-5"><FieldsEditor fields={fields} onChange={onChange} /></div><footer className="flex flex-wrap items-center justify-between gap-2 border-t border-[#e8e2da] bg-white px-4 py-3 sm:px-5"><button className="rounded-full bg-[#17151c] px-3.5 py-2 text-[11px] font-bold text-white transition-colors hover:bg-[#e44762]" type="button" onClick={onAdd}>+ Add field</button><button className="rounded-full border border-[#d8d2c8] px-3.5 py-2 text-[11px] font-bold text-[#514c47] transition-colors hover:border-[#17151c]" type="button" onClick={() => setOpen(false)}>Done</button></footer></section></div> : null}
  </>;
}

function PageNavigator({ pages, activeId, onSelect, onChange, onAdd, onRemove }: { pages: TemplatePage[]; activeId: string; onSelect: (id: string) => void; onChange: (pages: TemplatePage[]) => void; onAdd: () => void; onRemove: (id: string) => void }) {
  const [dragId, setDragId] = useState<string | null>(null);
  function move(id: string, direction: -1 | 1) { const index = pages.findIndex((page) => page.id === id); const target = index + direction; if (index < 0 || target < 0 || target >= pages.length) return; const next = [...pages]; [next[index], next[target]] = [next[target], next[index]]; onChange(next); }
  function drop(targetId: string) { if (!dragId || dragId === targetId) return; const from = pages.findIndex((page) => page.id === dragId); const to = pages.findIndex((page) => page.id === targetId); if (from < 0 || to < 0) return; const next = [...pages]; const [moved] = next.splice(from, 1); next.splice(to, 0, moved); onChange(next); setDragId(null); }
  return <SectionCard title="Pages" description="Each page has its own title, settings and ordered sections."><div className="flex gap-2 overflow-x-auto pb-1 lg:grid lg:grid-cols-3 lg:overflow-visible">{pages.map((page, index) => <div key={page.id} draggable onDragStart={() => setDragId(page.id)} onDragOver={(event) => event.preventDefault()} onDrop={() => drop(page.id)} onDragEnd={() => setDragId(null)} onClick={() => onSelect(page.id)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); onSelect(page.id); } }} role="button" tabIndex={0} className={`min-w-[210px] cursor-pointer rounded-[14px] border p-3 transition-colors focus:outline-none focus:ring-4 focus:ring-[#f8d9de] lg:min-w-0 ${activeId === page.id ? "border-[#17151c] bg-[#17151c] text-white" : "border-[#e3ddd4] bg-white text-[#423d38] hover:border-[#c8beb3]"} ${dragId === page.id ? "ring-2 ring-[#f3b8c0]" : ""}`.trim()}><div className="flex items-start gap-2"><div className="min-w-0 flex-1"><span className={`mb-2 block text-[10px] font-bold uppercase tracking-[0.12em] ${activeId === page.id ? "text-white/55" : "text-[#968d83]"}`.trim()}>Page {index + 1}</span><span className="block truncate text-[13px] font-bold">{page.title}</span><span className={`mt-1 block text-[11px] ${activeId === page.id ? "text-white/60" : "text-[#8e867e]"}`.trim()}>{page.blocks.length} sections · drag to move</span></div><button className={`grid size-7 shrink-0 place-items-center rounded-md border text-[14px] disabled:opacity-30 ${activeId === page.id ? "border-white/20 text-white/70 hover:text-white" : "border-transparent text-[#a59d94] hover:border-[#f0c7ce] hover:text-[#c63d58]"}`.trim()} type="button" aria-label={`Remove ${page.title}`} disabled={pages.length === 1} onClick={(event) => { event.stopPropagation(); onRemove(page.id); }}>×</button></div><div className="mt-3 flex items-center gap-1"><button className={`grid size-7 place-items-center rounded-md border text-[12px] disabled:opacity-30 ${activeId === page.id ? "border-white/20 text-white" : "border-[#e3ddd4] text-[#6a645d]"}`.trim()} type="button" aria-label="Move page up" disabled={index === 0} onClick={(event) => { event.stopPropagation(); move(page.id, -1); }}>←</button><button className={`grid size-7 place-items-center rounded-md border text-[12px] disabled:opacity-30 ${activeId === page.id ? "border-white/20 text-white" : "border-[#e3ddd4] text-[#6a645d]"}`.trim()} type="button" aria-label="Move page down" disabled={index === pages.length - 1} onClick={(event) => { event.stopPropagation(); move(page.id, 1); }}>→</button></div></div>)}</div><button className="mt-3 w-full rounded-[11px] border border-dashed border-[#d5cec4] bg-white px-3 py-2.5 text-[11px] font-bold text-[#6b635b] transition-colors hover:border-[#17151c] hover:text-[#17151c]" type="button" onClick={onAdd}>+ Add page</button></SectionCard>;
}

function PageSettingsEditor({ template, page, onChange }: { template: DocumentTemplateDraft; page: TemplatePage; onChange: (page: TemplatePage) => void }) {
  const custom = Object.keys(page.settings).length > 0;
  function update(settings: Partial<TemplatePageSettings>) { onChange({ ...page, settings: { ...page.settings, ...settings } }); }
  function setCustom(enabled: boolean) { onChange({ ...page, settings: enabled ? { marginTop: template.settings.marginTop, marginRight: template.settings.marginRight, marginBottom: template.settings.marginBottom, marginLeft: template.settings.marginLeft, stampGap: template.settings.stampGap, showPageNumbers: template.settings.showPageNumbers, fontFamily: template.settings.fontFamily, defaultFontSize: template.settings.defaultFontSize } : {} }); }
  return <SectionCard title="Current page" description="Rename this page and optionally override the global setup for it."><div className="grid gap-3 sm:grid-cols-2"><Field label="Page name" value={page.title} onChange={(title) => onChange({ ...page, title })} /><div className="flex items-end pb-1"><Toggle label="Use custom page settings" checked={custom} onChange={setCustom} /></div></div>{custom ? <div className="mt-4 grid gap-3 rounded-[13px] border border-[#e6dfd7] bg-white p-3 sm:grid-cols-2 lg:grid-cols-4"><Field label="Top (mm)" type="number" value={String(page.settings.marginTop ?? template.settings.marginTop)} onChange={(value) => update({ marginTop: Number(value) })} /><Field label="Right (mm)" type="number" value={String(page.settings.marginRight ?? template.settings.marginRight)} onChange={(value) => update({ marginRight: Number(value) })} /><Field label="Bottom (mm)" type="number" value={String(page.settings.marginBottom ?? template.settings.marginBottom)} onChange={(value) => update({ marginBottom: Number(value) })} /><Field label="Left (mm)" type="number" value={String(page.settings.marginLeft ?? template.settings.marginLeft)} onChange={(value) => update({ marginLeft: Number(value) })} /><Field label="Stamp gap (mm)" type="number" value={String(page.settings.stampGap ?? template.settings.stampGap)} onChange={(value) => update({ stampGap: Number(value) })} /><label className={labelClass}>Font family<select className={`${inputClass} mt-1.5`} value={page.settings.fontFamily ?? template.settings.fontFamily} onChange={(event) => update({ fontFamily: event.target.value as "serif" | "sans" })}><option value="serif">Classic serif</option><option value="sans">Clean sans</option></select></label><label className={labelClass}>Default size<select className={`${inputClass} mt-1.5`} value={page.settings.defaultFontSize ?? template.settings.defaultFontSize} onChange={(event) => update({ defaultFontSize: event.target.value as TemplateFontSize })}>{fontSizeOptions.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><div className="flex items-end pb-1"><Toggle label="Page number" checked={page.settings.showPageNumbers ?? template.settings.showPageNumbers} onChange={(showPageNumbers) => update({ showPageNumbers })} /></div><button className="text-left text-[11px] font-bold text-[#a33b51] hover:text-[#e44762] lg:col-span-4" type="button" onClick={() => setCustom(false)}>Reset this page to global settings</button></div> : <p className="mt-3 rounded-[11px] bg-[#f4f0ea] px-3 py-2.5 text-[11px] text-[#817970]">This page inherits the global paper, spacing and typography settings.</p>}</SectionCard>;
}

function Editor({ template, onChange, onSave, onPublish, onUnpublish, busy, busyAction, isNew, isPublished, isDirty, savedSlug, slugStatus, slugBusy, onCheckSlug }: { template: DocumentTemplateDraft; onChange: (template: DocumentTemplateDraft) => void; onSave: () => void; onPublish: () => void; onUnpublish: () => void; busy: boolean; busyAction: BusyAction; isNew: boolean; isPublished: boolean; isDirty: boolean; savedSlug: string; slugStatus: "unchecked" | "checking" | "available" | "taken" | "invalid"; slugBusy: boolean; onCheckSlug: () => void }) {
  const [activePageId, setActivePageId] = useState(template.pages[0]?.id ?? "");
  const activePage = template.pages.find((page) => page.id === activePageId) ?? template.pages[0];
  const previewValues = useMemo(() => Object.fromEntries(template.fields.map((field) => [field.key, `{{${field.key}}}`])), [template.fields]);
  const statusLabel = isNew ? "Local draft" : isPublished ? (isDirty ? "Live · edits pending" : "Published") : isDirty ? "Unsaved changes" : "Draft saved";
  const statusDescription = isNew ? "Create this draft to unlock its preview URL." : isPublished ? (isDirty ? "Your edits are private until you publish them." : "This version is live on the public page.") : isDirty ? "Changes are local until you save the draft." : "Saved privately. Publish when ready.";
  const statusClass = isNew ? "bg-[#f4eee8] text-[#85796d]" : isPublished && !isDirty ? "bg-[#e5f3e8] text-[#2d7650]" : isPublished ? "bg-[#fff3dc] text-[#94651f]" : isDirty ? "bg-[#fff0f2] text-[#b13c53]" : "bg-[#eef0f3] text-[#626a73]";
  const publishDisabled = busy || isNew || (isPublished && !isDirty);
  useEffect(() => { if (!template.pages.some((page) => page.id === activePageId)) setActivePageId(template.pages[0]?.id ?? ""); }, [activePageId, template.pages]);
  function patch(patchValue: Partial<DocumentTemplateDraft>) { onChange({ ...template, ...patchValue }); }
  function patchPage(nextPage: TemplatePage) { patch({ pages: template.pages.map((page) => page.id === nextPage.id ? nextPage : page) }); }
  function addPage() { const page = makePage(template.pages.length, activePage?.settings.defaultFontSize ?? template.settings.defaultFontSize); patch({ pages: [...template.pages, page] }); setActivePageId(page.id); }
  function removePage(id: string) { if (template.pages.length === 1) return; const index = template.pages.findIndex((page) => page.id === id); const pages = template.pages.filter((page) => page.id !== id); patch({ pages }); if (id === activePage?.id) setActivePageId(pages[Math.max(0, index - 1)]?.id ?? pages[0].id); }
  function addBlock(type: EditableBlockType) { if (!activePage) return; patchPage({ ...activePage, blocks: [...activePage.blocks, makeBlock(type, template.fields, activePage.blocks.length, activePage.settings.defaultFontSize ?? template.settings.defaultFontSize)] }); }
  const addButtons: Array<[EditableBlockType, string]> = [["heading", "+ Heading"], ["paragraph", "+ Text"], ["field", "+ Input"], ["spacer", "+ Spacer"], ["signature", "+ Signature"]];

  return <div className="grid min-w-0 gap-5 xl:grid-cols-[minmax(0,1.25fr)_minmax(320px,0.75fr)]"><div className="min-w-0 space-y-5"><div className="flex flex-wrap items-center justify-between gap-3 rounded-[14px] border border-[#e1dcd4] bg-white px-3.5 py-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.13em] text-[#8a8178]">Template page</p><p className="mt-1 text-[12px] text-[#817970]">{savedSlug ? `business-tools/templates/${savedSlug}` : "Save this draft to create its page URL."}</p></div>{savedSlug ? <div className="flex flex-wrap gap-2"><a className="rounded-full border border-[#d8d2c8] px-3 py-1.5 text-[11px] font-bold text-[#514c47] transition-colors hover:border-[#e44762] hover:text-[#e44762]" href={`/business-tools/templates/${encodeURIComponent(savedSlug)}?preview=1`} target="_blank" rel="noreferrer">Preview draft ↗</a>{isPublished ? <a className="rounded-full bg-[#17151c] px-3 py-1.5 text-[11px] font-bold text-white transition-colors hover:bg-[#e44762]" href={`/business-tools/templates/${encodeURIComponent(savedSlug)}`} target="_blank" rel="noreferrer">View live page ↗</a> : null}</div> : <span className="rounded-full bg-[#f4eee8] px-2.5 py-1.5 text-[10px] font-bold uppercase tracking-[0.1em] text-[#85796d]">Local draft</span>}</div>
    <SectionCard title="Template details" description="Start with a clear name. This local draft becomes a saved template when you create it."><div className="grid gap-3 sm:grid-cols-2"><Field label={isNew ? "Draft name" : "Template name"} value={template.title} onChange={(title) => patch({ title })} placeholder="Untitled template" /><div><span className={labelClass}>Public slug</span><div className="mt-1.5 flex gap-2"><input className={inputClass} value={template.slug} placeholder="office-rental-deed" onChange={(event) => patch({ slug: event.target.value.toLowerCase().replace(/[^a-z0-9-]/g, "-") })} /><button className="h-10 shrink-0 rounded-[11px] border border-[#d8d2c8] bg-white px-3 text-[11px] font-bold text-[#514c47] transition-colors hover:border-[#e44762] hover:text-[#e44762]" type="button" onClick={onCheckSlug} disabled={slugBusy}>{slugBusy ? "…" : "Check"}</button></div>{slugStatus === "available" ? <p className="mt-1.5 text-[11px] font-semibold text-[#2c7450]">Slug is available.</p> : slugStatus === "taken" ? <p className="mt-1.5 text-[11px] font-semibold text-[#c53e59]">Slug is already in use.</p> : slugStatus === "invalid" ? <p className="mt-1.5 text-[11px] font-semibold text-[#c53e59]">Use lowercase letters, numbers and hyphens.</p> : <p className="mt-1.5 text-[11px] text-[#958c82]">This becomes the public URL.</p>}</div><div className="sm:col-span-2"><Area label="Description" value={template.description} onChange={(description) => patch({ description })} /></div></div></SectionCard>
    <SectionCard title="Global page setup" description="These settings apply to every page unless a page chooses a custom override."><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className={labelClass}>Paper size<select className={`${inputClass} mt-1.5`} value={template.settings.paperSize} onChange={(event) => patch({ settings: { ...template.settings, paperSize: event.target.value as "A4" | "LEGAL" } })}><option value="A4">A4</option><option value="LEGAL">Legal</option></select></label><Field label="Top margin (mm)" type="number" value={String(template.settings.marginTop)} onChange={(value) => patch({ settings: { ...template.settings, marginTop: Number(value) } })} /><Field label="Right margin (mm)" type="number" value={String(template.settings.marginRight)} onChange={(value) => patch({ settings: { ...template.settings, marginRight: Number(value) } })} /><Field label="Bottom margin (mm)" type="number" value={String(template.settings.marginBottom)} onChange={(value) => patch({ settings: { ...template.settings, marginBottom: Number(value) } })} /><Field label="Left margin (mm)" type="number" value={String(template.settings.marginLeft)} onChange={(value) => patch({ settings: { ...template.settings, marginLeft: Number(value) } })} /><Field label="Stamp gap (mm)" type="number" value={String(template.settings.stampGap)} onChange={(value) => patch({ settings: { ...template.settings, stampGap: Number(value) } })} /><label className={labelClass}>Font family<select className={`${inputClass} mt-1.5`} value={template.settings.fontFamily} onChange={(event) => patch({ settings: { ...template.settings, fontFamily: event.target.value as "serif" | "sans" } })}><option value="serif">Classic serif</option><option value="sans">Clean sans</option></select></label><label className={labelClass}>Default text size<select className={`${inputClass} mt-1.5`} value={template.settings.defaultFontSize} onChange={(event) => patch({ settings: { ...template.settings, defaultFontSize: event.target.value as TemplateFontSize } })}>{fontSizeOptions.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label></div><div className="mt-3"><Toggle label="Show page numbers by default" checked={template.settings.showPageNumbers} onChange={(showPageNumbers) => patch({ settings: { ...template.settings, showPageNumbers } })} /></div></SectionCard>
    <section className="space-y-2"><div className="flex items-end justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.13em] text-[#2d7650]">Shared document content</p><h2 className="mt-0.5 font-brand text-[18px] font-bold tracking-[-0.025em] text-[#17151c]">Inputs</h2></div><span className="text-[11px] text-[#817970]">Not page-specific</span></div><TemplateInputsCard fields={template.fields} onChange={(fields) => patch({ fields })} onAdd={() => patch({ fields: [...template.fields, makeField("text", template.fields.length)] })} /></section>
    <PageNavigator pages={template.pages} activeId={activePage?.id ?? ""} onSelect={setActivePageId} onChange={(pages) => patch({ pages })} onAdd={addPage} onRemove={removePage} />
    {activePage ? <><PageSettingsEditor template={template} page={activePage} onChange={patchPage} /><SectionCard title={`Sections on ${activePage.title}`} description="Build this page from ordered sections. Drag the handle or use the arrows to rearrange them." action={<div className="flex flex-wrap gap-1.5">{addButtons.map(([type, label]) => <button className="rounded-full border border-[#ddd6cd] bg-white px-2.5 py-2 text-[10px] font-bold text-[#625c55] transition-colors hover:border-[#17151c] hover:text-[#17151c] disabled:cursor-not-allowed disabled:opacity-40" type="button" key={type} disabled={type === "field" && !template.fields.length} onClick={() => addBlock(type)}>{label}</button>)}</div>}><BlockList blocks={activePage.blocks} fields={template.fields} onChange={(blocks) => patchPage({ ...activePage, blocks })} /></SectionCard></> : null}
    <div className="sticky bottom-3 z-10 flex flex-col gap-3 rounded-[16px] border border-[#d9d3ca] bg-white/95 p-3 shadow-[0_12px_30px_rgba(44,36,31,0.1)] backdrop-blur sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${statusClass}`.trim()}>{statusLabel}</span>{isDirty && !isNew ? <span className="text-[12px] font-semibold text-[#817970]">Not yet published</span> : null}</div><p className="mt-1 text-[12px] leading-[1.4] text-[#817970]">{statusDescription}</p></div><div className="flex flex-wrap items-center gap-2 sm:justify-end"><button className="min-h-10 rounded-full border border-[#d8d1c8] px-4 text-[12px] font-bold text-[#514c47] transition-colors hover:border-[#17151c] disabled:cursor-not-allowed disabled:opacity-45" type="button" onClick={onSave} disabled={busy || (!isNew && !isDirty)}>{busyAction === "save" ? "Saving…" : isNew ? "Create draft" : "Save draft"}</button>{!isNew && isPublished ? <button className="min-h-10 rounded-full border border-[#f0c7ce] px-4 text-[12px] font-bold text-[#b13c53] transition-colors hover:border-[#e44762] hover:bg-[#fff7f8] disabled:cursor-not-allowed disabled:opacity-45" type="button" onClick={onUnpublish} disabled={busy}>{busyAction === "unpublish" ? "Unpublishing…" : "Unpublish"}</button> : null}{!isNew ? <button className="min-h-10 rounded-full bg-[#17151c] px-4 text-[12px] font-bold text-white transition-colors hover:bg-[#e44762] disabled:cursor-not-allowed disabled:opacity-45" type="button" onClick={onPublish} disabled={publishDisabled}>{busyAction === "publish" ? "Publishing…" : isPublished ? (isDirty ? "Publish changes" : "Published") : "Publish draft"}</button> : null}</div></div>
  </div><aside className="min-w-0 overscroll-contain xl:sticky xl:top-6 xl:max-h-[calc(100vh-3rem)] xl:overflow-y-auto xl:pr-1"><SectionCard title="Live preview" description="A4/Legal ratio is preserved at every width. Dynamic values appear as tokens until a user fills the document."><div className="mb-3 flex flex-wrap items-center justify-between gap-2 rounded-[11px] border border-[#e5dfd7] bg-[#faf8f4] px-3 py-2 text-[12px] text-[#817970]"><span>Template view · {template.settings.paperSize}</span><span className="font-semibold text-[#6b635b]"><code className="rounded bg-white px-1">{"{{field_key}}"}</code> = dynamic value</span></div><div className="min-w-0 overflow-x-auto"><DocumentTemplatePaper template={template} values={previewValues} showLabels={false} /></div></SectionCard></aside></div>;
}

type SlugStatus = "unchecked" | "checking" | "available" | "taken" | "invalid";
type BusyAction = "save" | "publish" | "unpublish" | null;

export function TemplateBuilderModule() {
  const [templates, setTemplates] = useState<AdminDocumentTemplate[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [savedSlug, setSavedSlug] = useState("");
  const [draft, setDraft] = useState<DocumentTemplateDraft | null>(null);
  const [revision, setRevision] = useState<number | null>(null);
  const [isPublished, setIsPublished] = useState(false);
  const [isNew, setIsNew] = useState(false);
  const [isDirty, setIsDirty] = useState(false);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [busyAction, setBusyAction] = useState<BusyAction>(null);
  const [slugBusy, setSlugBusy] = useState(false);
  const [slugStatus, setSlugStatus] = useState<SlugStatus>("unchecked");
  const [notice, setNotice] = useState("");
  const [error, setError] = useState("");

  function handleError(value: unknown) { if (value instanceof ApiError && value.status === 401) { window.location.assign("/admin/login"); return; } setError(value instanceof Error ? value.message : "Unable to load templates."); }
  function selectTemplate(template: AdminDocumentTemplate) { setSelectedId(template.id); setSavedSlug(template.slug); setDraft({ title: template.title, slug: template.slug, description: template.description, settings: template.settings, fields: template.fields, pages: template.pages }); setRevision(template.revision); setIsPublished(template.status === "PUBLISHED"); setIsNew(false); setIsDirty(false); setSlugStatus("unchecked"); setNotice(""); setError(""); }
  useEffect(() => { let active = true; void getAdminTemplates().then((items) => { if (!active) return; setTemplates(items); if (items[0]) selectTemplate(items[0]); }).catch((value) => { if (active) handleError(value); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  function startNew() { setSelectedId(null); setSavedSlug(""); setDraft(createBlankTemplate()); setRevision(null); setIsPublished(false); setIsNew(true); setIsDirty(true); setSlugStatus("unchecked"); setNotice(""); setError(""); }
  function changeDraft(next: DocumentTemplateDraft) { setIsDirty(true); setDraft((current) => { if (current?.slug !== next.slug) setSlugStatus("unchecked"); return next; }); }
  async function validateSlug(): Promise<boolean> {
    if (!draft) return false;
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(draft.slug)) { setSlugStatus("invalid"); return false; }
    setSlugBusy(true); setSlugStatus("checking");
    try { const result = await checkTemplateSlug(draft.slug, isNew ? undefined : selectedId ?? undefined); setSlugStatus(result.available ? "available" : "taken"); if (!result.available) setError("Choose another public slug before saving."); return result.available; }
    catch (value) { handleError(value); return false; }
    finally { setSlugBusy(false); }
  }
  async function save() {
    if (!draft || busy) return;
    setBusy(true); setBusyAction("save"); setNotice(""); setError("");
    try { if (!(await validateSlug())) return; const saved = isNew ? await createAdminTemplate(draft) : await updateAdminTemplate(selectedId!, draft, revision!); setTemplates((current) => isNew ? [saved, ...current] : current.map((item) => item.id === saved.id ? saved : item)); selectTemplate(saved); setNotice(isNew ? "Draft created." : "Draft saved."); }
    catch (value) { handleError(value); } finally { setBusy(false); setBusyAction(null); }
  }
  async function publish() {
    if (!selectedId || revision === null || !draft || busy) return;
    setBusy(true); setBusyAction("publish"); setNotice(""); setError("");
    try { if (!(await validateSlug())) return; const savedDraft = await updateAdminTemplate(selectedId, draft, revision); setTemplates((current) => current.map((item) => item.id === savedDraft.id ? savedDraft : item)); selectTemplate(savedDraft); const saved = await publishAdminTemplate(savedDraft.id, savedDraft.revision); setTemplates((current) => current.map((item) => item.id === saved.id ? saved : item)); selectTemplate(saved); setNotice("Template published."); }
    catch (value) { handleError(value); } finally { setBusy(false); setBusyAction(null); }
  }
  async function unpublish() { if (!selectedId || revision === null || busy) return; setBusy(true); setBusyAction("unpublish"); setNotice(""); setError(""); try { const saved = await unpublishAdminTemplate(selectedId, revision); setTemplates((current) => current.map((item) => item.id === saved.id ? saved : item)); selectTemplate(saved); setNotice("Template unpublished."); } catch (value) { handleError(value); } finally { setBusy(false); setBusyAction(null); } }

  if (loading) return <div className="grid min-h-[360px] place-items-center rounded-[22px] border border-[#e1dcd4] bg-white text-[13px] font-semibold text-[#817970]">Loading templates…</div>;
  return <div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[0.16em] text-[#e44762]">Business tools / templates</p><h2 className="mt-1 font-brand text-[30px] font-bold tracking-[-0.04em] text-[#17151c]">Build documents once.</h2><p className="mt-1 max-w-[640px] text-[13px] leading-[1.5] text-[#817970]">Organize each document as pages and sections, then publish a polished form for users to complete.</p></div><button className="min-h-11 rounded-full bg-[#17151c] px-5 text-[13px] font-bold text-white transition-colors hover:bg-[#e44762]" type="button" onClick={startNew}>+ New template</button></div>{error ? <p className="rounded-[12px] border border-[#f0c7ce] bg-[#fff8f8] px-3.5 py-3 text-[12px] font-semibold text-[#c53e59]" role="alert">{error}</p> : null}{notice ? <p className="rounded-[12px] border border-[#c7dfce] bg-[#eff8f1] px-3.5 py-3 text-[12px] font-semibold text-[#2d7650]" role="status">{notice}</p> : null}<div className="grid min-w-0 gap-5 lg:grid-cols-[260px_minmax(0,1fr)]"><aside className="min-w-0 rounded-[18px] border border-[#e1dcd4] bg-white p-3"><div className="mb-2 flex items-center justify-between px-2"><span className="text-[10px] font-bold uppercase tracking-[0.13em] text-[#8a8178]">Templates</span><span className="text-[11px] text-[#a09991]">{templates.length}</span></div><div className="flex gap-2 overflow-x-auto pb-1 lg:block lg:space-y-1 lg:overflow-visible">{templates.map((template) => <button className={`min-w-[210px] rounded-[12px] p-3 text-left transition-colors lg:block lg:w-full ${selectedId === template.id ? "bg-[#17151c] text-white" : "bg-[#faf8f4] text-[#423d38] hover:bg-[#f3eee8]"}`.trim()} type="button" key={template.id} onClick={() => selectTemplate(template)}><span className="block truncate text-[13px] font-bold">{template.title}</span><span className={`mt-1 block truncate text-[10px] ${selectedId === template.id ? "text-white/60" : "text-[#8e867e]"}`.trim()}>{template.status === "PUBLISHED" ? "Published" : "Draft"} · {template.paperSize}</span></button>)}</div></aside><div className="min-w-0">{draft ? <Editor template={draft} onChange={changeDraft} onSave={() => void save()} onPublish={() => void publish()} onUnpublish={() => void unpublish()} busy={busy} busyAction={busyAction} isNew={isNew} isPublished={isPublished} isDirty={isDirty} savedSlug={savedSlug} slugStatus={slugStatus} slugBusy={slugBusy} onCheckSlug={() => void validateSlug()} /> : <div className="rounded-[18px] border border-dashed border-[#d5cec4] bg-white p-8 text-center text-[13px] text-[#817970]">Choose a template or create a new one.</div>}</div></div></div>;
}
