import { feeSources, money, taxCategoryLabels, type ToolDefinition, type ToolValues, type ToolsConfig } from "@/lib/business-tools";
import styles from "./tools.module.css";

export function ToolRules({ tool, config, year, values }: { tool: ToolDefinition; config: ToolsConfig | null; year: string; values?: ToolValues }) {
  if (tool.group === "builder") return <div className={styles.rules}><section className={styles.ruleCard}><h2 className={styles.panelTitle}>A clear draft, ready for review.</h2><p>Fill in the parties and the terms they have agreed. Check the preview, then generate a downloadable draft. Rental and partnership deeds are available in English and Bangla.</p><p>These templates are starting points, not legal advice or government-approved forms. Before signing or filing, have a qualified professional check the terms, stamp duty, witnesses, registration and execution requirements. MOA/AOA is a working outline, not a complete incorporation instrument.</p></section><section className={styles.ruleCard}><h2 className={styles.panelTitle}>Your document stays private.</h2><p>Drafts are processed to generate your document, but are not saved to your account or the admin panel. Only details you explicitly include in a service request are stored. Refreshing this page clears unsaved entries.</p></section></div>;
  if (!config) return <p className={styles.muted}>Connect to the backend to load the published rules.</p>;
  const tax = config.settings.taxYears.find((item) => item.year === year) ?? config.settings.taxYears[0];
  if (tool.slug === "income-tax") return <div className={styles.rules}>
    <section className={styles.ruleCard}><h2 className={styles.panelTitle}>Tax-free thresholds · {tax.year}</h2><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th scope="col">Taxpayer category</th><th scope="col">Annual threshold</th></tr></thead><tbody>{Object.entries(tax.thresholds).map(([key, value]) => <tr key={key}><td>{taxCategoryLabels[key as keyof typeof taxCategoryLabels]}</td><td>{money(value)}</td></tr>)}</tbody></table></div><p>An eligible parent or guardian can add {money(tax.childAllowance)} for each qualifying child with a disability. Both parents cannot claim for the same child.</p></section>
    <section className={styles.ruleCard}><h2 className={styles.panelTitle}>Progressive tax bands</h2><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th scope="col">Income above your threshold</th><th scope="col">Rate</th></tr></thead><tbody>{tax.bands.map((band, index) => <tr key={index}><td>{band.width === null ? "Remaining income" : `Next ${money(band.width)}`}</td><td>{band.rate}%</td></tr>)}</tbody></table></div></section>
    <section className={styles.ruleCard}><h2 className={styles.panelTitle}>Exemptions, rebate and minimum tax</h2><p>Private employment exemption: one-third of employment income, capped at {money(tax.salaryExemptionCap)}. Already-computed taxable income receives no further salary exemption.</p><p>Investment rebate is the lowest of {tax.rebateIncomeRate}% of eligible taxable income, {tax.rebateInvestmentRate}% of qualifying investment, or {money(tax.rebateCap)}. Enter investments after their individual eligibility limits.</p><p>When income exceeds the threshold, the minimum tax is {money(tax.minimumTax)}, or {money(tax.newTaxpayerMinimum)} for a qualifying new taxpayer. The calculator applies the minimum after rebate, then subtracts adjustable credits.</p><p>Special income, turnover-based minimum tax, surcharges and late filing adjustments need a separate review. Excess credits are not a guaranteed refund.</p><p><a className={styles.textLink} href={tax.sourceUrl} target="_blank" rel="noreferrer">View the source ↗</a> · Settings version {config.version}</p></section>
  </div>;
  if (tool.slug === "vat") return <div className={styles.rules}><section className={styles.ruleCard}><h2 className={styles.panelTitle}>One rate. Two ways to calculate.</h2><p>Choose the VAT period and supply type, then use either basis: excluding VAT gives VAT = base amount × rate ÷ 100; including VAT finds the base amount by dividing the total by 1 + rate ÷ 100.</p><p>The standard rate is 15%. Supply-specific exemptions or reduced rates may apply; enter the applicable rate. Zero-rated and exempt supplies are legally different, even though 0% produces the same arithmetic here. This is not a VAT return or Mushak invoice generator.</p><p><a className={styles.textLink} href="https://nbr.gov.bd/faq/vat-faq" target="_blank" rel="noreferrer">NBR VAT guidance ↗</a></p></section></div>;
  const fee = config.settings.fees[tool.slug as keyof typeof config.settings.fees];
  if (tool.slug === "limited-company") {
    const companyFees = config.settings.companyRegistration;
    return <div className={styles.rules}>
      <section className={styles.ruleCard}><h2 className={styles.panelTitle}>What your estimate includes</h2><p>Enter authorised capital and the name-clearance choice. The calculator applies the published RJSC schedule automatically, then adds the Limex professional service fee.</p><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th scope="col">Charge</th><th scope="col">Reference</th></tr></thead><tbody><tr><td>RJSC filing fee · 6 documents</td><td>{money(companyFees.filingFee)}</td></tr><tr><td>MoA stamp</td><td>{money(companyFees.moaStamp)}</td></tr>{companyFees.aoaStampBands.map((band, index) => <tr key={`aoa-${index}`}><td>AoA stamp · {band.upto === null ? "above the last tier" : `up to ${money(band.upto)}`}</td><td>{money(band.amount)}</td></tr>)}<tr><td>Authorised capital fee</td><td>Calculated by tier</td></tr><tr><td>Name clearance</td><td>{money(companyFees.nameClearanceFee)} per name</td></tr></tbody></table></div></section>
      <section className={styles.ruleCard}><h2 className={styles.panelTitle}>Current RJSC reference</h2><p>{companyFees.note}</p><p><a className={styles.textLink} href={companyFees.sourceUrl} target="_blank" rel="noreferrer">Open RJSC fee schedule ↗</a> · Reference date {companyFees.effectiveDate} · Settings version {config.version}</p></section>
    </div>;
  }
  if (tool.slug === "trade-license") {
    const authorityKey = values?.authority === "Dhaka South City Corporation" ? "dscc" : "dncc";
    const schedule = config.settings.tradeLicense[authorityKey];
    const selectedTariff = schedule.tariffRows.find((row) => row.key === values?.businessType);
    return <div className={styles.rules}>
      <section className={styles.ruleCard}><h2 className={styles.panelTitle}>{authorityKey === "dscc" ? "DSCC" : "DNCC"} estimate basis</h2><p>{schedule.note}</p><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th scope="col">Charge</th><th scope="col">Reference</th></tr></thead><tbody><tr><td>Selected business tariff</td><td>{selectedTariff?.amount === null || selectedTariff?.amount === undefined ? "Authority assessment" : money(selectedTariff.amount)} / year</td></tr><tr><td>Limited company tariff</td><td>Based on paid-up capital</td></tr><tr><td>Business identification signboard</td><td>{money(schedule.signboardRates.identificationPerSqFt)} / sq. ft.</td></tr><tr><td>Illuminated advertisement</td><td>{money(schedule.signboardRates.illuminatedPerSqFt)} / sq. ft.</td></tr><tr><td>Non-illuminated advertisement</td><td>{money(schedule.signboardRates.nonIlluminatedPerSqFt)} / sq. ft.</td></tr><tr><td>LED advertisement</td><td>{money(schedule.signboardRates.ledPerSqFt)} / sq. ft.</td></tr><tr><td>VAT planning rate</td><td>{schedule.vatRate}%</td></tr><tr><td>Application form · licence book · other fee</td><td>{money(schedule.formFee)} · {money(schedule.bookFee)} · {money(schedule.otherFee)}</td></tr></tbody></table></div><p><a className={styles.textLink} href={schedule.sourceUrl} target="_blank" rel="noreferrer">Open {authorityKey === "dscc" ? "DSCC" : "DNCC"} e-revenue portal ↗</a> · <a className={styles.textLink} href={feeSources["trade-license"]} target="_blank" rel="noreferrer">Open the official model schedule ↗</a> · Schedule date {schedule.effectiveDate} · Settings version {config.version}</p></section>
      <section className={styles.ruleCard}><h2 className={styles.panelTitle}>Limited-company fee bands</h2><p>When the business structure is private limited or one-person company, the selected business activity is retained for context and the annual fee uses paid-up capital bands.</p><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th scope="col">Paid-up capital</th><th scope="col">Annual fee</th></tr></thead><tbody>{schedule.limitedCompanyBands.map((band, index) => <tr key={`trade-capital-${index}`}><td>{band.upto === null ? "Above previous tier" : `Up to ${money(band.upto)}`}</td><td>{money(band.amount)}</td></tr>)}</tbody></table></div></section>
      <section className={styles.ruleCard}><h2 className={styles.panelTitle}>Full tariff catalogue</h2><p>These seeded rows cover the published business categories used by the calculator. Administrators can add or revise a row when the authority publishes a change.</p><details><summary className="cursor-pointer text-[12px] font-semibold">Show all {schedule.tariffRows.filter((row) => !row.key.startsWith("limited-company-")).length} business rows</summary><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th scope="col">Business category</th><th scope="col">Annual fee</th></tr></thead><tbody>{schedule.tariffRows.filter((row) => !row.key.startsWith("limited-company-")).map((row) => <tr key={row.key}><td>{row.label}</td><td>{row.amount === null ? "Authority assessment" : money(row.amount)}</td></tr>)}</tbody></table></div></details></section>
      <section className={styles.ruleCard}><h2 className={styles.panelTitle}>What can change the final total</h2><p>Licence and renewal fee, signboard / advertisement tax, VAT, source tax, arrears, book value, form fee, other fee and late-renewal surcharge are kept as separate rows. A renewal surcharge uses the higher of the fixed monthly amount or the configured percentage of the annual licence fee after the grace month.</p><p>Source tax and arrears are not universal; leave them blank or at zero only when the authority assessment confirms that. This calculator is a planning estimate, not a payment receipt.</p></section>
    </div>;
  }
  if (tool.slug === "trademark") return <div className={styles.rules}>
    <section className={styles.ruleCard}><h2 className={styles.panelTitle}>Choose the protection you need</h2><p>Enter the brand name, applicant type, mark type, filing stage and Nice classes. Goods generally use classes 1–34 and services use classes 35–45; repeated class numbers are counted once.</p><p>Search, application, publication, registration and renewal are separate stages. The calculator uses the government amount per selected class and does not check availability.</p></section>
    <section className={styles.ruleCard}><h2 className={styles.panelTitle}>Keep the estimate transparent</h2><p>Government fees and Limex support are shown separately. Add other charges only when they are confirmed for the filing.</p><p><a className={styles.textLink} href={fee.sourceUrl} target="_blank" rel="noreferrer">DPDT reference ↗</a> · Settings version {config.version}</p></section>
  </div>;
  if (tool.slug === "rjsc") return <div className={styles.rules}>
    <section className={styles.ruleCard}><h2 className={styles.panelTitle}>Select the RJSC service</h2><p>Use this standalone estimate for company registration, name clearance, annual return, director or shareholder changes, share transfer, office changes or capital increases. Entity type and capital are context for the authority’s assessment.</p></section>
    <section className={styles.ruleCard}><h2 className={styles.panelTitle}>Registration is not availability</h2><p>RJSC charges vary by service and filing details. A blank assessment remains pending and a request lets Limex confirm the right fee with you.</p><p><a className={styles.textLink} href={fee.sourceUrl} target="_blank" rel="noreferrer">RJSC fee calculator ↗</a> · Settings version {config.version}</p></section>
  </div>;
  if (tool.slug === "irc-erc") return <div className={styles.rules}>
    <section className={styles.ruleCard}><h2 className={styles.panelTitle}>Match the certificate to the trade</h2><p>Choose Commercial IRC, Industrial IRC or ERC, then select import, export or both and new registration or renewal. IRC applications need the annual import ceiling shown on the relevant assessment.</p><p>Chamber membership, bank fees, late fees and other approvals are not added automatically. Keep them in the assessed or other-charge fields only when confirmed.</p></section>
    <section className={styles.ruleCard}><h2 className={styles.panelTitle}>Confirm with CCI&amp;E</h2><p><a className={styles.textLink} href={fee.sourceUrl} target="_blank" rel="noreferrer">CCI&amp;E reference ↗</a> · Settings version {config.version}</p></section>
  </div>;
  return <div className={styles.rules}><section className={styles.ruleCard}><h2 className={styles.panelTitle}>Know what’s included.</h2><p>{fee.note}</p><p>Enter your assessed amounts to calculate a budget. Blank fees are shown as pending, not zero. Limex support and government charges are separate. If an admin has set a reference fee, confirm that it applies to your specific case.</p><p>Capital and import ceilings describe your application; they are not additional fees and do not automatically set a tariff. The authority’s assessment is needed for a confirmed government amount.</p><p>{fee.effectiveDate ? `Reference fee effective from ${fee.effectiveDate}. ` : "No verified default government amount has been published. "}<a className={styles.textLink} href={fee.sourceUrl} target="_blank" rel="noreferrer">Authority reference ↗</a></p></section><section className={styles.ruleCard}><h2 className={styles.panelTitle}>From estimate to next step.</h2><p>A callback request asks Limex to review your needs. It does not book a confirmed appointment, check registry availability, reserve a name or submit an official application.</p></section></div>;
}
